name = "solana-rpc-proxy"
main = "src/index.ts"
compatibility_date = "2023-02-02"
kv_namespaces = [
  { binding = "SOLANA_TX", id = "b8162d76b4034c42be7d0d975d7e1252", preview_id = "96d66758e0c84694b2155b9fa188e43c" }
]

[vars]
SOLANA_RPC_ENDPOINT = "https://path.to.your.rpc.endpoint/"
