name: Deploy

on:
  workflow_dispatch:
    inputs:
      commit:
        description: "Commit SHA to Deploy (defaults to latest)"
        required: false
      target:
        description: "Build target"
        required: true
        default: "aarch64-unknown-linux-gnu"

run-name: Deploy ${{ github.event.inputs.commit || github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - id: setup
        uses: actions/github-script@v7
        with:
          script: |
            core.setOutput('commit_sha', '${{ github.event.inputs.commit || github.sha }}');

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.setup.outputs.commit_sha }}

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ github.event.inputs.target }}

      - name: Install Cross
        shell: bash
        run: |
          curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
          cargo binstall --no-confirm cross

      - name: Build Binary
        run: cross build --verbose --locked --release --target ${{ github.event.inputs.target }}
